#pragma once

//from GLFW
#define SAKURA_MOUSE_BUTTON_1         0
#define SAKURA_MOUSE_BUTTON_2         1
#define SAKURA_MOUSE_BUTTON_3         2
#define SAKURA_MOUSE_BUTTON_4         3
#define SAKURA_MOUSE_BUTTON_5         4
#define SAKURA_MOUSE_BUTTON_6         5
#define SAKURA_MOUSE_BUTTON_7         6
#define SAKURA_MOUSE_BUTTON_8         7
#define SAKURA_MOUSE_BUTTON_LAST      SAKURA_MOUSE_BUTTON_8
#define SAKURA_MOUSE_BUTTON_LEFT      SAKURA_MOUSE_BUTTON_1
#define SAKURA_MOUSE_BUTTON_RIGHT     SAKURA_MOUSE_BUTTON_2
#define SAKURA_MOUSE_BUTTON_MIDDLE    SAKURA_MOUSE_BUTTON_3